server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mopl
    username: mopl_user
    password: mopl1234
  jpa:
    properties:
      hibernate:
        format_sql: true
  batch:
    job:
      enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security: trace

management:
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

tmdb:
  api:
    key: d7385e5ab4d0b92709739f77fccd7612
    base-url: https://api.themoviedb.org

Sports:
  api:
    key: 123
    base-url: https://www.thesportsdb.com/api/v1/json

mopl:
  mail:
    type: smtp