server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mopl
    username: mopl_user
    password: mopl1234
  jpa:
    properties:
      hibernate:
        format_sql: true
  batch:
    job:
      enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security: trace
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level [%thread] traceId=%X{traceId:-} : %logger{36} - %msg%n"


management:
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
